/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGoalsMonthlyRouteImport } from './routes/_app.goals-monthly'
import { Route as AppGoalsWeeklyRouteImport } from './routes/_app.goals-weekly'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppTensesRouteImport } from './routes/_app.tenses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsMonthlyRoute = AppGoalsMonthlyRouteImport.update({
  id: '/goals-monthly',
  path: '/goals-monthly',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsWeeklyRoute = AppGoalsWeeklyRouteImport.update({
  id: '/goals-weekly',
  path: '/goals-weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTensesRoute = AppTensesRouteImport.update({
  id: '/tenses',
  path: '/tenses',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals-monthly': typeof AppGoalsMonthlyRoute
  '/goals-weekly': typeof AppGoalsWeeklyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/tenses': typeof AppTensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals-monthly': typeof AppGoalsMonthlyRoute
  '/goals-weekly': typeof AppGoalsWeeklyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/tenses': typeof AppTensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals-monthly': typeof AppGoalsMonthlyRoute
  '/_app/goals-weekly': typeof AppGoalsWeeklyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/tenses': typeof AppTensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/goals-monthly'
    | '/goals-weekly'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/tenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/goals-monthly'
    | '/goals-weekly'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/tenses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/goals-monthly'
    | '/_app/goals-weekly'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/tenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals-monthly': {
      id: '/_app/goals-monthly'
      path: '/goals-monthly'
      fullPath: '/goals-monthly'
      preLoaderRoute: typeof AppGoalsMonthlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals-weekly': {
      id: '/_app/goals-weekly'
      path: '/goals-weekly'
      fullPath: '/goals-weekly'
      preLoaderRoute: typeof AppGoalsWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenses': {
      id: '/_app/tenses'
      path: '/tenses'
      fullPath: '/tenses'
      preLoaderRoute: typeof AppTensesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsMonthlyRoute: typeof AppGoalsMonthlyRoute
  AppGoalsWeeklyRoute: typeof AppGoalsWeeklyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTensesRoute: typeof AppTensesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsMonthlyRoute: AppGoalsMonthlyRoute,
  AppGoalsWeeklyRoute: AppGoalsWeeklyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTensesRoute: AppTensesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
